name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    
    - name: Test
      run: dotnet test $(SolutionDir)bin\$(Configuration)\apitests.dll --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: DOTNET Tests            # Name of the check run which will be created
        path: reports/test-results.trx    # Path to test results
        reporter: dotnet-trx       # Format of test results
        list-tests: 'all'
        fail-on-error: 'true'
        artifact: /test-results(.*)/
